import { Schema, model } from "mongoose";

const roomsSchema = new Schema({
  avgRating: Number,
  listingBathroomLabel: String,
  bathrooms: Number,
  listingBedLabel: String,
  bedrooms: Number,
  beds: Number,
  businessHostLabel: Object,
  city: String,
  configurableContent: Object,
  contextualPicturesPageInfo: {
    hasNextPage: Boolean,
    endCursor: String,
  },
  emergencyMessage: Object,
  listingFloatingMessage: Object,
  formattedBadges: Array, //check if not working
  listingGuestLabel: String,
  id: String,
  isAutoTranslated: Boolean,
  isNewListing: Boolean,
  isSuperhost: Boolean,
  relaxedFilterLabels: Object,
  localizedCityName: String,
  localizedDistanceText: String,
  locationTitle: String,
  locationContext: Object,
  listingName: String,
  listingObjType: String,
  neighborhood: Object,
  listingPreviewAmenityNames: Array,
  previewTags: Array,
  publicAddress: String,
  reviews: Array,
  reviewsCount: Number,
  richKickers: Object,
  roomType: String,
  roomTypeCategory: String,
  roomTypeId: Object,
  spaceType: String,
  starRating: Number,
  summary: Object,
  wishlistedCount: Object,
  title: String,
  avgRatingLocalized: String,
  accessibilityLabel: String,
  concatQualifierLeft: Boolean,
  price: String,
  qualifier: String,
  trailingContent: Object,
  adults: Number,
  children: Number,
  infants: Number,
  checkin: String,
  checkout: String,
  relaxedAmenityIds: Object,
  categoryTag: String,
  pets: Number,
  location: {
    mapBoundsHint: {
      northeast: {
        latitude: Number,
        longitude: Number,
      },
      southwest: {
        latitude: Number,
        longitude: Number,
      },
    },
    fallbackMapCenter: Object,
  },
  verified: {
    enabled: Boolean,
    badgeText: String,
    badgeSecondaryText: String,
    kickerBadgeType: String,
  },
  images: Array,
});

const Rooms = model("Rooms", roomsSchema);
export default Rooms;
